# Generated by Django 6.0.6 on 2026-06-09 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('CRYPTO', 'Cryptocurrency')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20, max_length=20)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20, max_length=20)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20, max_length=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20, max_length=20)),
                ('volume', models.BigIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='analyzer.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]
